### ISSUE TITLE
Integration test/examples are failing

### ISSUE THREAD

**Issue by peol** [qlik-oss/enigma.js#456]
We need to investigate, especially before release of a new version since this potentially indicates a broken npm package on master right now.

```bash
Starting example: basics/events/generated-apis.js
/examples/node_modules/enigma.js/enigma.js:1230
      this.openedPromise = undefined$7;
                           ^

ReferenceError: undefined$7 is not defined
    at new RPC (/examples/node_modules/enigma.js/enigma.js:1230:28)
    at Function.getSession (/examples/node_modules/enigma.js/enigma.js:2527:19)
    at Function.create (/examples/node_modules/enigma.js/enigma.js:2552:20)
    at module.exports (/examples/session.js:6:31)
    at Object.<anonymous> (/examples/basics/events/generated-apis.js:3:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Ending example: basics/events/generated-apis.js

Starting example: basics/events/session.js
/examples/node_modules/enigma.js/enigma.js:1230
      this.openedPromise = undefined$7;
                           ^

ReferenceError: undefined$7 is not defined
    at new RPC (/examples/node_modules/enigma.js/enigma.js:1230:28)
    at Function.getSession (/examples/node_modules/enigma.js/enigma.js:2527:19)
    at Function.create (/examples/node_modules/enigma.js/enigma.js:2552:20)
    at module.exports (/examples/session.js:6:31)
    at Object.<anonymous> (/examples/basics/events/session.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Ending example: basics/events/session.js

Starting example: basics/lists/app-object-list.js
/examples/node_modules/enigma.js/enigma.js:1230
      this.openedPromise = undefined$7;
                           ^

ReferenceError: undefined$7 is not defined
    at new RPC (/examples/node_modules/enigma.js/enigma.js:1230:28)
    at Function.getSession (/examples/node_modules/enigma.js/enigma.js:2527:19)
    at Function.create (/examples/node_modules/enigma.js/enigma.js:2552:20)
    at module.exports (/examples/session.js:6:31)
    at Object.<anonymous> (/examples/basics/lists/app-object-list.js:15:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Ending example: basics/lists/app-object-list.js
```

**Comment by peol** [comment]
Regression in rollup: https://github.com/rollup/rollup/issues/2290

Should be fixed in an upcoming version.
